name: Test self hosted runner
on: [push]
jobs:
  Test-Self-Hosted-Runner:
    runs-on: self-hosted
    steps:
      - run: echo "ğŸ‰ self-hosted runner ã§å®Ÿè¡Œã•ã‚ŒãŸã‚ˆï¼"
      - name: checkout
        uses: actions/checkout@v3
      - run: echo "The ${{ github.repository }} repository has been cloned to the runner"
      - name: List files in repository
        run: |
          ls ${{ github.workspace }}
